---
title: "Yale Athletic Department Data"
author: "425/625"
date: '2023-11-13'
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

The Yale Athletic department collects a variety of biomedical and performance data for their athletes. These data come from a variety of software packages and sources, are formatted differently, and currently in separate spreadsheets, .csv files, Google sheets, etc.  The strength and conditioning coaches, who work with a variety of Yale athletes from multiple sports, are interested in creating a more unified database which can be used to create dashboards and perform analyses that they are not currently possible given the state of their data. 

As a start, they are interested in combining the force plate data and GPS data, and creating a dashboard. See the email below for more details. 

> Here is a breakdown of the types of data we collect across many of our teams, and the method of how it is gathered:
>
> Manual collection placed into Google Sheets:
>
>- Bodyweights
>- RPE (Exhaustion scale)
>- Lift Selections
>- Rogue Echo Bike Watts
> 
> Download from Software platforms through CSV files (also placed into Google Sheets with query functions used to create dashboards):
>
> - Catapult GPS Data from Practice and Games
> - Hawkins Force Plate Jump Metrics
> - Teambuildr (our workout delivery software) – reps, sets, weights, exercises
> - 1080 Sprint Data from Speed Workouts
> 
> Within the database I am imagining, each row of data would be labeled with the athlete name, date or session, and data type - followed by the actual data. The CSV downloads usually are in this structure, but in different formats. I believe there may be a way to code an autoformat to have all data be consistent.
>
> The two most important of all of these data points for us that we would want to compare are the GPS Data and Force Plate Data. With how their CSVs are formatted, this may also be the easiest starting point for the students in creating the database. From there can continue to add other types of data in and make adjustments as needed.
>
> As far as webapps or dashboards we would like to create, I may need some more time and to collaborate with some of the other coaches to come up with an idea. I have attached a video from a former football player Seun Omonije who created this webapp and a dashboard that is very similar to what we would be looking to make that looks at our force plate data.

## Deliverables

1. Join the force plate and GPS data as described above. 

2. Create a dashboard similar to the one shown in the video, with dropdowns for Name, Position, and Date. You can work on either the rectangular player card or the table, but you do not need to do both. You do not need a file upload button. Assume they will be using your data from #1. 

3. Submit your code for joining the data, the joined data, and your app to Gradescope. 

The data (.csv and .xlsx) and video (.mp4) files are in our GitHub repo. 
 
Work in pairs. Join forces with someone who wasn't in your Gymnastics group. 